# NOTE: settings in this file have precedence over settings on the website
image: Visual Studio 2013

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

matrix:
  fast_finish: true

platform:
  - Win32
  - x64

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

configuration:
  - Debug
#  - Release

environment:
  matrix:
    - TOOLCHAIN_VERSION: 12.0
      solution_name: win_build\boinc_vs2013.sln
      depends_git_path: http://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git
      depends_path: C:\projects\boinc_depends_win_vs2013

cache:
  - C:\projects\boinc_depends_win_vs2013

before_build:
  - call win_build\load_dependencies.bat %depends_git_path% %depends_path% %platform% %configuration%
  - if %TOOLCHAIN_VERSION%==12.0 call "%VS120COMNTOOLS%\vsvars32.bat"

build_script:
  - devenv %solution_name% /Build "%configuration%|%platform%"

test: off

# Artifacts path C:\projects\boinc\win_build\.\Build\x64\Debug\wrapper_6.1_windows_x86_64.exe is not a relative path. Please set it relative to the build folder C:\projects\boinc 

artifacts:
- path: '**\wrapper*.exe'
- path: win_build\Build\x64\Debug\wrapper_6.1_windows_x86_64.exe
- path: win_build\Build\x64\*\wrapper_6.1_windows_x86_64.exe
